### ISSUE TITLE
Failed validator smart contract call while running

### ISSUE THREAD

**Issue by edusu** [besu-eth/besu#6742]
### Description
I have come to receive an error in the validator nodes concerning that the call to the validator contract fails (the management of the network validators is done by me onChain).
It occurs when there is a high load on the transaction network, since RPC requests are made to nodes other than the validator and each one is in a pod. It is alleviated by increasing the rpc-http-max-active-connections option, but increasing the load always reaches a point where the error occurs when there is an overload of transactions in the network. The tests have been done with my own connector for besu from hyperledger caliper. With nodes with both bonsai and forest databases, bonsai reaches the overload point earlier. The nodes have a resource limit of 500m cpu and 1 gb of memory. The version of hyperledger besu used is 24.3.0.

2024-03-15 10:50:27 #                                                                                                  #
2024-03-15 10:50:27 # Besu version 24.3.0                                                                              #
2024-03-15 10:50:27 #                                                                                                  #
2024-03-15 10:50:27 # Configuration:                                                                                   #
2024-03-15 10:50:27 # Network: Custom genesis file                                                                     #
2024-03-15 10:50:27 # /etc/genesis/genesis.json                                                                        #
2024-03-15 10:50:27 # Network Id: 1337                                                                                 #
2024-03-15 10:50:27 # Data storage: Forest                                                                             #
2024-03-15 10:50:27 # Sync mode: Full                                                                                  #
2024-03-15 10:50:27 # RPC HTTP APIs: DEBUG,ETH,ADMIN,WEB3,IBFT,NET,TRACE,EEA,PRIV,QBFT,PERM,TXPOOL                     #
2024-03-15 10:50:27 # RPC HTTP port: 8545                                                                              #
2024-03-15 10:50:27 # Using LAYERED transaction pool implementation                                                    #
2024-03-15 10:50:27 # Using STACKED worldstate update mode                                                             #
2024-03-15 10:50:27 #                                                                                                  #
2024-03-15 10:50:27 # Host:                                                                                            #
2024-03-15 10:50:27 # Java: openjdk-java-17                                                                            #
2024-03-15 10:50:27 # Maximum heap size: 0.24 GB                                                                       #
2024-03-15 10:50:27 # OS: linux-x86_64                                                                                 #
2024-03-15 10:50:27 # glibc: 2.35                                                                                      #
2024-03-15 10:50:27 # jemalloc: 5.2.1-0-gea6b3e973b477b8061e0076bb257dbd7f3faa756                                      #
2024-03-15 10:50:27 # Total memory: 15.46 GB                                                                           #
2024-03-15 10:50:27 # CPU cores: 16                                                                                    #
2024-03-15 10:50:27 #                                                                                                  #
2024-03-15 10:50:27 # Plugins:                                                                                         #
2024-03-15 10:50:27 # TOTAL = 0 of 0 plugins successfully loaded                                                       #
2024-03-15 10:50:27 # from /opt/besu/plugins                                                                           #
2024-03-15 10:50:27 #          

The validators contract is very simple and I understand that the function that fails is the interface one:
function getValidators() external view returns (address[] memory);
Which in our case returns the data structure of the validators array.
Being a network overload problem I am not clear if it is a bug as such, I hope it helps. The error is not fatal and the execution continues, it only happens during times of heavy network load and after that it works without errors.

### Logs (if a bug)
The error stack trace:

2024-03-14 14:46:10.012+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | QbftBesuControllerBuilder | Imported #328 / 0 tx / 1554 pending / 0 (0.0%) gas / (0x6f1e082024435ccdd3750badd56c0fbd6fdd9185435b1dbb98caa319c6534113)
2024-03-14 14:46:12.020+00:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Block 329 (0x3ab8781fd66a986f274b93afe969ec86a76d4ef1f20788576193ca7e4e06b846) is already imported
2024-03-14 14:46:12.021+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | QbftBesuControllerBuilder | Produced #329 / 0 tx / 1554 pending / 0 (0.0%) gas / (0x3ab8781fd66a986f274b93afe969ec86a76d4ef1f20788576193ca7e4e06b846)
2024-03-14 14:46:14.014+00:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Imported #330 / 0 tx / 0 om / 0 (0.0%) gas / (0x070bb9fbd9983bf3d1775c734fa34af6ae809e3c6b2a819fc0a89b9dbcff3d27) in 0.003s. Peers: 10
2024-03-14 14:46:14.022+00:00 | BftProcessorExecutor-QBFT-0 | ERROR | EventMultiplexer | State machine threw exception while processing event \{org.hyperledger.besu.consensus.common.bft.events.BftReceivedMessageEvent@74112304\}
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Failed validator smart contract call
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2087)
        at com.google.common.cache.LocalCache.get(LocalCache.java:4036)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4950)
        at org.hyperledger.besu.consensus.qbft.validator.TransactionValidatorProvider.getValidatorsFromContract(TransactionValidatorProvider.java:86)
        at org.hyperledger.besu.consensus.qbft.validator.TransactionValidatorProvider.getValidatorsAfterBlock(TransactionValidatorProvider.java:71)
        at org.hyperledger.besu.consensus.qbft.validator.ForkingValidatorProvider.getValidatorsAfterBlock(ForkingValidatorProvider.java:67)
        at org.hyperledger.besu.consensus.qbft.validator.ForkingValidatorProvider.getValidatorsAtHead(ForkingValidatorProvider.java:61)
        at org.hyperledger.besu.consensus.common.bft.network.ValidatorPeers.getLatestValidators(ValidatorPeers.java:114)
        at org.hyperledger.besu.consensus.common.bft.network.ValidatorPeers.send(ValidatorPeers.java:86)
        at org.hyperledger.besu.consensus.common.bft.UniqueMessageMulticaster.send(UniqueMessageMulticaster.java:66)
        at org.hyperledger.besu.consensus.qbft.QbftGossip.send(QbftGossip.java:83)
        at org.hyperledger.besu.consensus.common.bft.statemachine.BaseBftController.consumeMessage(BaseBftController.java:125)
        at org.hyperledger.besu.consensus.qbft.statemachine.QbftController.handleMessage(QbftController.java:95)
        at org.hyperledger.besu.consensus.common.bft.statemachine.BaseBftController.handleMessageEvent(BaseBftController.java:88)
        at org.hyperledger.besu.consensus.common.bft.EventMultiplexer.handleBftEvent(EventMultiplexer.java:53)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at org.hyperledger.besu.consensus.common.bft.BftProcessor.run(BftProcessor.java:65)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.IllegalStateException: Failed validator smart contract call
        at org.hyperledger.besu.consensus.qbft.validator.ValidatorContractController.lambda$getValidators$0(ValidatorContractController.java:77)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at org.hyperledger.besu.consensus.qbft.validator.ValidatorContractController.getValidators(ValidatorContractController.java:77)
        at org.hyperledger.besu.consensus.qbft.validator.TransactionValidatorProvider.lambda$getValidatorsFromContract$0(TransactionValidatorProvider.java:89)
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4955)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3589)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2328)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2187)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2081)
        ... 19 more
2024-03-14 14:46:16.015+00:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Block 331 (0x377c79621c871d5b597d51927e12749ec83e4338b0b3691d1330a9a7ba7f3790) is already imported
2024-03-14 14:46:16.016+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | QbftBesuControllerBuilder | Imported #331 / 0 tx / 1554 pending / 0 (0.0%) gas / (0x377c79621c871d5b597d51927e12749ec83e4338b0b3691d1330a9a7ba7f3790)
2024-03-14 14:46:18.012+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | QbftBesuControllerBuilder | Imported #332 / 0 tx / 1554 pending / 0 (0.0%) gas / (0xbaed7b952ea8d927d6164b42ef3ec278a1ec0a38486cf5a709294daa821c18f1)
2024-03-14 14:46:20.012+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | QbftBesuControllerBuilder | Produced #333 / 0 tx / 1554 pending / 0 (0.0%) gas / (0x5721516d0f7118157533e8813615e904710c380a2ba2089d9e1d61657e4517a4)

### Genesis file
{
      "config": {
        "chainId": 1337,
        "homesteadBlock": 0,
        "eip150Block": 0,
        "eip155Block": 0,
        "eip158Block": 0,
        "byzantiumBlock": 0,
        "constantinopleBlock": 0,
        "constantinopleFixBlock": 0,
        "istanbulBlock": 0,
        "muirGlacierBlock": 0,
        "berlinBlock": 0,
        "londonBlock": 0,
        "arrowGlacierBlock": 0,
        "grayGlacierBlock": 0,
        "parisBlock": 0,
        "zeroBaseFee": true,
        "qbft": {
          "blockperiodseconds": 2,
          "epochlength": 30000,
          "requesttimeoutseconds": 4,
          "validatorcontractaddress": "0x0000000000000000000000000000000000007777"
        }
      },
      "nonce": "0x0",
      "timestamp": "0x65ba2eda",
      "gasLimit": "0xf7b760",
      "difficulty": "0x1",
      "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
      "coinbase": "0x0000000000000000000000000000000000000000",
      "alloc": {
...
},
      "extraData": "0xe5a00000000000000000000000000000000000000000000000000000000000000000c0c080c0"
    }

### Versions (Add all that apply)
Docker image of besu 24.3.0 running in local kubernetes

### Smart contract information (If you're reporting an issue arising from deploying or calling a smart contract, please supply related information)
* Solidity version 0.8.18

**Comment by IvanovVenko** [comment]
Hi, 
we have similar issue with Besu version 25.1.0  too:
under load (about 6000 relatively big transactions in the pending queue) the validator node fails to retrieve it's status as a validator from the validator's smart contract (Consensys).

The bad thing is that there is no recovery, so even after restart the issue reoccurs (as seen in the log). 
Maybe 25.4.0 will help resolve this bad persistency - we are testing at the moment, but the fact that the issue happens needs to be sesolved as it can block the whole network.

2025-04-07 13:32:21.049+00:00 | main | ERROR | Runner | unable to start main loop
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Failed validator smart contract call
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2085)
        at com.google.common.cache.LocalCache.get(LocalCache.java:4017)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4898)
        at org.hyperledger.besu.consensus.qbft.validator.TransactionValidatorProvider.getValidatorsFromContract(TransactionValidatorProvider.java:86)
        at org.hyperledger.besu.consensus.qbft.validator.TransactionValidatorProvider.getValidatorsAfterBlock(TransactionValidatorProvider.java:71)
        at org.hyperledger.besu.consensus.qbft.validator.ForkingValidatorProvider.getValidatorsAfterBlock(ForkingValidatorProvider.java:66)
        at org.hyperledger.besu.consensus.qbft.validator.ForkingValidatorProvider.getValidatorsAtHead(ForkingValidatorProvider.java:60)
        at org.hyperledger.besu.consensus.common.bft.statemachine.BftFinalState.getValidators(BftFinalState.java:93)
        at org.hyperledger.besu.consensus.common.bft.statemachine.BftFinalState.isLocalNodeValidator(BftFinalState.java:130)
        at org.hyperledger.besu.consensus.qbft.core.statemachine.QbftBlockHeightManagerFactory.create(QbftBlockHeightManagerFactory.java:69)
        at org.hyperledger.besu.consensus.qbft.core.statemachine.QbftController.createNewHeightManager(QbftController.java:118)
        at org.hyperledger.besu.consensus.common.bft.statemachine.BaseBftController.startNewHeightManager(BaseBftController.java:210)
        at org.hyperledger.besu.consensus.common.bft.statemachine.BaseBftController.start(BaseBftController.java:79)
        at org.hyperledger.besu.consensus.common.bft.blockcreation.BftMiningCoordinator.start(BftMiningCoordinator.java:101)
        at org.hyperledger.besu.controller.QbftBesuControllerBuilder$1.onInitialSyncCompleted(QbftBesuControllerBuilder.java:319)
        at org.hyperledger.besu.util.Subscribers.lambda$forEach$0(Subscribers.java:131)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.hyperledger.besu.util.Subscribers.forEach(Subscribers.java:128)
        at org.hyperledger.besu.ethereum.eth.sync.state.SyncState.markInitialSyncPhaseAsDone(SyncState.java:326)
        at org.hyperledger.besu.ethereum.eth.sync.DefaultSynchronizer.start(DefaultSynchronizer.java:234)
        at org.hyperledger.besu.Runner.startEthereumMainLoop(Runner.java:177)
        at org.hyperledger.besu.cli.BesuCommand.run(BesuCommand.java:986)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at org.hyperledger.besu.cli.BesuCommand.lambda$createExecuteTask$0(BesuCommand.java:893)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at org.hyperledger.besu.cli.BesuCommand.lambda$createPluginRegistrationTask$1(BesuCommand.java:902)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at org.hyperledger.besu.cli.util.ConfigDefaultValueProviderStrategy.execute(ConfigDefaultValueProviderStrategy.java:58)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at org.hyperledger.besu.cli.BesuCommand.executeCommandLine(BesuCommand.java:929)
        at org.hyperledger.besu.cli.BesuCommand.parse(BesuCommand.java:872)
        at org.hyperledger.besu.Besu.main(Besu.java:43)
Caused by: java.lang.IllegalStateException: Failed validator smart contract call
        at org.hyperledger.besu.consensus.qbft.validator.ValidatorContractController.lambda$getValidators$0(ValidatorContractController.java:77)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at org.hyperledger.besu.consensus.qbft.validator.ValidatorContractController.getValidators(ValidatorContractController.java:77)
        at org.hyperledger.besu.consensus.qbft.validator.TransactionValidatorProvider.lambda$getValidatorsFromContract$0(TransactionValidatorProvider.java:89)
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4903)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3574)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2316)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2189)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2079)
        ... 38 more
2025-04-07 13:32:21.051+00:00 | main | ERROR | Besu
....

**Comment by Mughira12** [comment]
@IvanovVenko Did you find any solutions to recover the nodes ? I having the same issue in a running network on besu24.7.0 , suddenly any node that is started shows the error, the validator nodes that are functioning show 6.9k txs pending but are not processing them

**Comment by v0dev** [comment]
Hi @edusu @IvanovVenko , were you able to bring back up the nodes ? I am facing the same issue currently and unable to startup nodes properly.
